### PR TITLE
Sort lib files to ensure consistent inclusion

### PR DESCRIPTION
**Pull request by paulj**
I'n looking to commit the generated output from bashly into my source repository so that I can easily fetch it within other scripts. The generated bashly script has some other dependencies in my repository, so whilst I'd like to push it somewhere to publish, this doesn't work all that cleanly.

So that I can make sure that the file is always updated, I've added a test run by my CI server that confirms the committed version matches a freshly built one - this will cause my CI to fail if I've forgotten to commit an update. However, I'm seeing CI failures because my local MacOS machine is ordering the content imported from `lib/` differently to how my CircleCI instance is.

This PR just adds a `sort` onto the files found in the `lib/` directory to ensure consistent ordering.

### CODE REVIEW

**Comment by DannyBen** [comment]
Alright. I see no problem with this.

I will merge and rerun tests (since running them on the PR as is, the approvals will probably fail).

**Comment by paulj** [comment]
Awesome - thanks for the super-quick turnaround! Apologies about the tests - I didn't fully look into how to run those.

**Comment by DannyBen** [comment]
No worries, you did perfectly (in fact no approval tests regeneration needed).

I will release a new version with this and #105 in a few minutes. Stand by.

Thanks for catching this - I also usually like to sort files in such cases.

**Comment by DannyBen** [comment]
0.6.6. is published on rubygems and dockerhub.

**Comment by paulj** [comment]
Great - thanks again!

**Pull request merged**
