### PR TITLE
Add support for tweaking production/development output

### PR DESCRIPTION
**Pull request by DannyBen**
cc #576, #575

This PR adds these options to the settings:

```yaml
# allowed values: always, never, production, development
enable_header_comment: always
enable_bash3_bouncer: always
enable_view_markers: development
enable_inspect_args: development
enable_deps_array: always
enable_env_var_names_array: always
```

This allows the user to define which of these features is rendered in which environment.

### CODE REVIEW

**Comment by DannyBen** [comment]
@EmilyGraceSeville7cf - made some additions to `settings.json` schema, if you can review:

https://github.com/DannyBen/bashly/pull/577/files#diff-b9a6f3c13822475db181e711b42460b9b8b9afd20973dec5fd81e7f4ff3ebc45

**Comment by EmilyGraceSeville7cf** [comment]
@DannyBen, I will review it in several hours.😀 I have checked linked issues and I can say for sure that I love this idea of having such settings added.

**Comment by DannyBen** [comment]
@EmilyGraceSeville7cf - note that I have just made the settings.json schema generate from YAML (in support/schemas folder), like we did with schemas/bashly.yml. It renders with 2 spaces instead of 4, this is why when viewing the diff without "Hide whitespaces", it looks like it was all changed.

**Review by EmilyGraceSeville7cf — APPROVED** [review]
LGTM 😄

**Pull request merged**
