### PR TITLE
Add support for private commands

### LINKED ISSUE #149: Feature request: allow sub-commands to be hidden from help text
Hi, @DannyBen! :wave: 

We are happy users of Bashly at @kolonialno, having written much of our internal data science tooling with it, thanks a lot! :bow: Let me start by explaining what I want to _achieve_ in order to prevent us having an [XY Problem](https://xyproblem.info/) on our hands.

## Problem to be solved

We are starting to amass a lot of sub-commands in on of our internal CLIs, and would like to clean up the help text and logic a bit. For instance, one of our commands `cli_name sub_command <arg>` is in practice just some glorified switch logic which invokes either `cli_name sub_command_arg1`, `cli_name sub_command_arg2`, or `cli_name sub_command_arg3` based on the value of `<arg>`. In fact, we intend our internal users to never invoke `cli_name sub_command_arg{1,2,3}` directly, and only invoke it through `cli_name sub_command`. We could in theory move the logic of the sub-commands into library functions, but then we lose all the nice tooling provided by Bashly for those commands; argument parsing and validation, and dependency checking come to mind.

## Proposed solution

If bashly provided an additional optional key in the `command` object configuration, let's say `hidden: true`, which excludes the given sub-command from the output of `cli_name` and `cli_name --help`, but still allows the command to be directly executed with `cli_name sub_command` and documentation with `cli_name sub_command --help`.

Another use-case for this parameter would be to release sub-commands in "Beta mode", hidden from most users, but you can do a soft launch by letting a subset of the CLI users know that the new sub-command is available on direct invocation.

## Alternative solution

Another solution that comes to mind is something more along the lines of "library functions" only for commands instead. Perhaps a command could be annotated as a "library command" or "private command", making it exclusively available in the namespace of the command implementations, but not outside from the perspective of the CLI user.

Thanks in advance,
Jakob

### PR DESCRIPTION
**Pull request by DannyBen**
- [x] Implementation
- [x] Specs / Example
- [x] Docs

Closes #149

### CODE REVIEW

**Comment by wolfgang42** [comment]
That was quick! Just tried it out and it looks like exactly what I wanted, my help message is much less cluttered now.

**Comment by DannyBen** [comment]
Alright - cool. 
I will implement specs/example then, and give 24 hours for the OP to comment.
I will cut a version tomorrow unless there will be objections/requests from anyone.

**Comment by JakobGM** [comment]
Sorry for the late reply, thank you so much, this looks good :relaxed:

**Comment by DannyBen** [comment]
Great. New release will happen sometime in the next few days, possibly tomorrow.
Just waiting for some decisions on the two open PRs.

**Pull request merged**
